### use rule provider and proxy provider



mixed-port: 7890
allow-lan: true
mode: rule
external-controller: "0.0.0.0:9090"
bind-address: "*"
proxy-providers:
  custom:
    type: "http"
    path: "./proxies/custom.yaml"
    url: "https://sub.com/link.txt"
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  hongkong:
    type: "http"
    path: "./proxies/hongkong.yaml"
    url: "https://sub.com/link.txt"
    interval: 86400
    filter: "é¦™æ¸¯"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  taiwan:
    type: "http"
    path: "./proxies/taiwan.yaml"
    url: "https://sub.com/link.txt"
    interval: 86400
    filter: "å°æ¹¾"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  japan:
    type: "http"
    path: "./proxies/japan.yaml"
    url: "https://sub.com/link.txt"
    interval: 86400
    filter: "æ—¥æœ¬"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  usa:
    type: "http"
    path: "./proxies/usa.yaml"
    url: "https://sub.com/link.txt"
    interval: 86400
    filter: "ç¾å›½"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  singapore:
    type: "http"
    path: "./proxies/singapore.yaml"
    url: "https://sub.com/link.txt"
    interval: 86400
    filter: "æ–°åŠ å¡"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  korean:
    type: "http"
    path: "./proxies/korean.yaml"
    url: "https://sub.com/link.txt"
    interval: 86400
    filter: "éŸ©å›½"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    use:
      - custom
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - DIRECT
  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    use:
      - custom
  - name: ğŸ“º å¤©ä½¿åŠ¨æ¼«
    type: select
    url: https://r2.hfyrw.com  
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - DIRECT
  - name: ğŸ“º å·´å“ˆå§†ç‰¹
    type: select
    proxies:
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ“º å“”å“©å“”å“©æ¸¯æ¾³å°
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ“¢ è°·æ­ŒFCM
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ® Steamå¹³å°
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - DIRECT
  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  - name: ğŸ¤– OpenAI
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - DIRECT
  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸƒ åº”ç”¨å‡€åŒ–
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸ† AdBlock
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - DIRECT
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    use:
      - hongkong
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    use:
      - taiwan
  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    use:
      - singapore
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    use:
      - japan
  - name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    use:
      - korean
  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 3600
    use:
      - usa
rule-providers:
  LocalAreaNetwork:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/LocalAreaNetwork.list"
    path: ./ruleset/LocalAreaNetwork.txt
    interval: 86400
    proxy: DIRECT    
    format: text    
  UnBan:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/UnBan.list"
    path: ./ruleset/UnBan.txt
    interval: 86400
    proxy: DIRECT    
    format: text    
  BanAD:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/BanAD.list"
    path: ./ruleset/BanAD.txt
    interval: 86400
    proxy: DIRECT    
    format: text    
  BanProgramAD:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/BanProgramAD.list"
    path: ./ruleset/BanProgramAD.txt
    interval: 86400
    proxy: DIRECT    
    format: text    
  BanEasyList:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/BanEasyList.list"
    path: ./ruleset/BanEasyList.txt
    interval: 86400    
    proxy: DIRECT    
    format: text
  BanEasyListChina:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/BanEasyListChina.list"
    path: ./ruleset/BanEasyListChina.txt
    interval: 86400
    proxy: DIRECT    
    format: text
  GoogleFCM:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Ruleset/GoogleFCM.list"
    path: ./ruleset/GoogleFCM.txt
    interval: 86400   
    proxy: DIRECT    
    format: text      
  GoogleCN:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/GoogleCN.list"
    path: ./ruleset/GoogleCN.txt
    interval: 86400 
    proxy: DIRECT    
    format: text    
  OpenAI:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/hzhq1255/my-clash-config-rule/clash/ruleset/OpenAI.list"
    path: ./ruleset/OpenAI.txt
    interval: 86400 
    proxy: DIRECT    
    format: text    
  Microsoft:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Microsoft.list"
    path: ./ruleset/Microsoft.txt
    interval: 86400   
    proxy: DIRECT    
    format: text      
  Apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Apple.list"
    path: ./ruleset/Apple.txt
    interval: 86400 
    proxy: DIRECT    
    format: text    
  Telegram:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Telegram.list"
    path: ./ruleset/Telegram.txt
    interval: 86400 
    proxy: DIRECT    
    format: text    
  Steam:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Ruleset/Steam.list"
    path: ./ruleset/Steam.txt
    interval: 86400 
    proxy: DIRECT    
    format: text    
  TSDM:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/hzhq1255/my-clash-config-rule/clash/ruleset/TSDM.list"
    path: ./ruleset/TSDM.txt
    interval: 86400     
    proxy: DIRECT    
    format: text      
  Bahamut:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Ruleset/Bahamut.list"
    path: ./ruleset/Bahamut.txt
    interval: 86400  
    proxy: DIRECT    
    format: text     
  BilibiliHMT:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/Ruleset/BilibiliHMT.list"
    path: ./ruleset/BilibiliHMT.txt
    interval: 86400   
    proxy: DIRECT    
    format: text    
  ProxyMedia:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/ProxyMedia.list"
    path: ./ruleset/ProxyMedia.txt
    interval: 86400   
    proxy: DIRECT    
    format: text    
  ProxyLite:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/ProxyLite.list"
    path: ./ruleset/ProxyLite.txt
    interval: 86400  
    proxy: DIRECT    
    format: text     
  MyProxyDomain:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/hzhq1255/my-clash-config-rule/clash/ruleset/MyProxyDomain.list"
    path: ./ruleset/MyProxyDomain.txt
    interval: 86400   
    proxy: DIRECT    
    format: text    
  ChinaDomain:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/ChinaDomain.list"
    path: ./ruleset/ChinaDomain.txt
    interval: 86400   
    proxy: DIRECT    
    format: text    
  ChinaCompanyIp:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR/Clash/ChinaCompanyIp.list"
    path: ./ruleset/ChinaCompanyIp.txt
    interval: 86400 
    proxy: DIRECT    
    format: text    

rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,UnBan,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,BanAD,ğŸ›‘ å…¨çƒæ‹¦æˆª
  - RULE-SET,BanProgramAD,ğŸƒ åº”ç”¨å‡€åŒ–
  - RULE-SET,BanEasyList,ğŸ† AdBlock
  - RULE-SET,BanEasyListChina,ğŸ† AdBlock
  - RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒFCM
  - RULE-SET,GoogleCN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,OpenAI,ğŸ¤– OpenAI
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥ä¿¡æ¯
  - RULE-SET,Steam,ğŸ® Steamå¹³å°
  - RULE-SET,TSDM,ğŸ“º å¤©ä½¿åŠ¨æ¼«  
  - RULE-SET,Bahamut,ğŸ“º å·´å“ˆå§†ç‰¹
  - RULE-SET,BilibiliHMT,ğŸ“º å“”å“©å“”å“©æ¸¯æ¾³å°
  - RULE-SET,ProxyMedia,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,MyProxyDomain,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,ProxyLite,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,MyProxyDomain,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,ChinaDomain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaCompanyIp,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,LAN,ğŸ¯ å…¨çƒç›´è¿
  - GEOIP,CN,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
